export type RootStackParamList = {
    HomeScreen: undefined;
    ItemDetailsScreen: {id: string};
    AddressScreen: undefined;
    UploadScreen: undefined;
    ConfirmUploadScreen: undefined;
    RequestScreen: {id: string};
    ConfirmRequestScreen: {id: string};
    FavouriteScreen: undefined;
    MessageScreen: undefined;
    ReviewScreen: {id: string};
    ProfileScreen: undefined;
    SettingScreen: undefined;
    EditProfileScreen: undefined;
    EditAddressScreen: undefined;
    ChangePasswordScreen: undefined;
    VerificationScreen: undefined;
    NotificationSettingsScreen: undefined;
    PrivacySettingsScreen: undefined;
    HelpCentreScreen: undefined;
    ContactUsScreen: undefined;
    CommunityRulesScreen: undefined;
    TipsScreen: undefined;
    FAQScreen: undefined;
    AboutScreen: undefined;
    RoadmapScreen: undefined;
    TNCScreen: undefined;
    PrivacyPolicyScreen: undefined;
    AnalyticsListedScreen: {id: string};
    AnalyticsReservedScreen: {id: string};
    AnalyticsDonatedScreen: {id: string};
    EditItemDetailsScreen: {id: string};
    ReviewToDonorScreen: undefined;
    ReviewToTakerScreen: undefined;
    ConfirmReviewToDonorScreen: undefined;
    ConfirmReviewToTakerScreen: undefined;
};