export type RootStackParamList = {
    HomeScreen: undefined;
    ItemDetailsScreen: {id: string};
    AddressScreen: undefined;
    FavouriteScreen: undefined;
    MessageScreen: undefined;
    ReviewScreen: {id: string};
    ProfileScreen: undefined;
    SettingScreen: undefined;
    EditProfileScreen: undefined;
    EditAddressScreen: undefined;
    ChangePasswordScreen: undefined;
    VerificationScreen: undefined;
    NotificationSettingsScreen: undefined;
    PrivacySettingsScreen: undefined;
    HelpCentreScreen: undefined;
    ContactUsScreen: undefined;
    CommunityRulesScreen: undefined;
    TipsScreen: undefined;
    FAQScreen: undefined;
    AboutScreen: undefined;
    RoadmapScreen: undefined;
    TNCScreen: undefined;
    PrivacyPolicyScreen: undefined;
    };